# ===== General =====
unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind r source-file ~/.tmux.conf \; display "Config recargada"

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on        # renumber windows when one is closed
set -g detach-on-destroy off      # don't exit tmux when closing a session

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g mouse on
set -g history-limit 1000000
set -sg escape-time 0
set -g set-clipboard on           # use system clipboard
setw -g mode-keys vi

# ===== Splits =====
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# ===== Vim-style pane navigation =====
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# ===== Tema: tmux-gruvbox =====
set -g status-position top

# ===== Plugins =====
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'egel/tmux-gruvbox'

set -g @tmux-gruvbox 'dark'

set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'

# ===== Shell =====
set -g default-shell /usr/sbin/zsh
set -g default-command "/usr/sbin/zsh -l"

run '~/.tmux/plugins/tpm/tpm'

# título de ventana, para que Hyprland detecte nvim
set -g set-titles on
set -g set-titles-string "#{pane_current_command}"
set -g status-interval 1
